// <auto-generated />
using System;
using System.Collections.Generic;
using McsCore.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace McsCore.Migrations
{
    [DbContext(typeof(McsAppDbContext))]
    [Migration("20251007171403_NewSnmpTcpDataRow")]
    partial class NewSnmpTcpDataRow
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("McsCore.Entities.Alarms", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParameterName")
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Threshold")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("McsCore.Entities.OidMapping", b =>
                {
                    b.Property<Guid>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Oid")
                        .HasColumnType("text");

                    b.Property<string>("ParameterName")
                        .HasColumnType("text");

                    b.Property<Guid?>("SnmpDeviceId")
                        .HasColumnType("uuid");

                    b.HasKey("ParameterId");

                    b.HasIndex("SnmpDeviceId");

                    b.ToTable("OidMapping");
                });

            modelBuilder.Entity("McsCore.Entities.Scripts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Script")
                        .HasColumnType("text");

                    b.Property<string>("ScriptName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("McsCore.Entities.SnmpDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Retry")
                        .HasColumnType("integer");

                    b.Property<int>("SnmpVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Timeout")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SnmpDevices");
                });

            modelBuilder.Entity("McsCore.Entities.TcpData", b =>
                {
                    b.Property<Guid>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ParameterName")
                        .HasColumnType("text");

                    b.Property<string>("Request")
                        .HasColumnType("text");

                    b.Property<Guid?>("TcpDeviceId")
                        .HasColumnType("uuid");

                    b.HasKey("ParameterId");

                    b.HasIndex("TcpDeviceId");

                    b.ToTable("TcpData");
                });

            modelBuilder.Entity("McsCore.Entities.TcpDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<List<string>>("TcpFormat")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("TcpDevices");
                });

            modelBuilder.Entity("McsCore.Entities.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("McsCore.Entities.OidMapping", b =>
                {
                    b.HasOne("McsCore.Entities.SnmpDevice", null)
                        .WithMany("OidList")
                        .HasForeignKey("SnmpDeviceId");
                });

            modelBuilder.Entity("McsCore.Entities.TcpData", b =>
                {
                    b.HasOne("McsCore.Entities.TcpDevice", null)
                        .WithMany("TcpData")
                        .HasForeignKey("TcpDeviceId");
                });

            modelBuilder.Entity("McsCore.Entities.SnmpDevice", b =>
                {
                    b.Navigation("OidList");
                });

            modelBuilder.Entity("McsCore.Entities.TcpDevice", b =>
                {
                    b.Navigation("TcpData");
                });
#pragma warning restore 612, 618
        }
    }
}
